### ISSUE TITLE
Implement Undo/Redo

### ISSUE THREAD

**Issue by vedant-pandey** [vedant-pandey/fralo-tech#49]
**Is your feature request related to a problem? Please describe.**
Editing on dnd builder does not support undo and redo functionality currently

**Describe the solution you'd like**
Implement undo and redo stacks

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vedant-pandey** [comment]
Undo and redo exist in the top bar but are not binded to undo/redo keystrokes

**Comment by ranitripathi5** [comment]
Please assign this issue to me.

**Comment by vedant-pandey** [comment]
Done @ranitripathi5
